name: test

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.6"
            os: ubuntu-20.04
            tox_env: "py36"
          - python: "3.6"
            os: windows-latest
            tox_env: "py36"
          - python: "3.7"
            tox_env: "py37"
          - python: "3.8"
            tox_env: "py38"
          - python: "3.9"
            tox_env: "py39"
        exclude:
          - python: "3.6"
            os: "windows-latest"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
